name: Homebrew release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  bump-homebrew-core:
    # Skip prereleases (homebrew-core only accepts stable)
    if: ${{ !contains(github.event.release.tag_name, '-') }}
    runs-on: macos-latest
    steps:
      - name: Derive version and source URL
        id: meta
        run: |
          TAG="${{ github.event.release.tag_name }}"
          # Strip leading 'v' for version
          VERSION="${TAG#v}"
          REPO="${{ github.repository }}"
          URL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Bump formula in homebrew-core
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_CORE_TOKEN }}
        run: |
          set -euxo pipefail
          FORMULA="caesiumclt"

          # Keep Homebrew up to date and ensure core is tapped
          brew update-reset
          brew tap homebrew/core

          # Create PR to homebrew-core updating url/sha256 for the new tag.
          # bump-formula-pr will compute the sha256 automatically for the given URL
          # and open a PR from your fork to Homebrew/homebrew-core.
          brew bump-formula-pr \
            --no-browse \
            --strict \
            --message="${FORMULA} ${{
              steps.meta.outputs.version
            }}" \
            --url="${{ steps.meta.outputs.url }}" \
            --fork-org="${{ github.actor }}" \
            "${FORMULA}"

      - name: Note on skipped prerelease
        if: ${{ failure() && contains(github.event.release.tag_name, '-') }}
        run: echo "Skipped prerelease tag ${{ github.event.release.tag_name }} (homebrew-core accepts only stable)."