name: Homebrew core bump

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  bump-homebrew-core:
    # Skip prereleases (homebrew-core only accepts stable)
    if: ${{ !contains(github.event.release.tag_name, '-') }}
    runs-on: macos-latest
    steps:
      - name: Derive version and source URL
        id: meta
        run: |
          TAG="${{ github.event.release.tag_name }}"
          # Strip leading 'v' for version
          VERSION="${TAG#v}"
          REPO="${{ github.repository }}"
          URL="https://github.com/${REPO}/archive/refs/tags/${TAG}.tar.gz"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Bump formula in homebrew-core
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_CORE_TOKEN }}
        run: |
          set -euxo pipefail
          FORMULA="caesiumclt"

          # Ensure Homebrew is up-to-date and core is tapped
          brew update-reset
          brew tap homebrew/core

          # Open PR to Homebrew/homebrew-core updating url/sha256 for the new tag.
          # bump-formula-pr will compute the sha256 automatically for the provided URL.
          brew bump-formula-pr \
            --no-browse \
            --strict \
            --message="${FORMULA} ${{ steps.meta.outputs.version }}" \
            --url="${{ steps.meta.outputs.url }}" \
            --fork-org="${{ github.repository_owner }}" \
            "${FORMULA}"